In [3]:
%pip install dlt[duckdb]

Collecting dlt[duckdb]
  Using cached dlt-1.6.1-py3-none-any.whl.metadata (11 kB)
Collecting PyYAML>=5.4.1 (from dlt[duckdb])
  Using cached PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: click>=7.1 in /home/abrham/Desktop/Datatalks/DataTalks-Data-engineering-Training/week-one/.venv/lib/python3.12/site-packages (from dlt[duckdb]) (8.1.8)
Collecting duckdb>=0.9 (from dlt[duckdb])
  Using cached duckdb-1.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (966 bytes)
Collecting fsspec>=2022.4.0 (from dlt[duckdb])
  Using cached fsspec-2025.2.0-py3-none-any.whl.metadata (11 kB)
Collecting gitpython>=3.1.29 (from dlt[duckdb])
  Using cached GitPython-3.1.44-py3-none-any.whl.metadata (13 kB)
Collecting giturlparse>=0.10.0 (from dlt[duckdb])
  Using cached giturlparse-0.12.0-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting hexbytes>=0.2.2 (from dlt[duckdb])
  Using cached hexbytes-1.3.0-py3-none-any.whl.metadata (3.3 kB)
Collecting humanize>=4.4.0 (from dlt[duckdb])
  Using cached humanize-4.12.0-py3-none-any.whl.metadata (7.8 kB)
Collecting jsonpath-ng>=1.5.3 (from dlt[duckdb])
  Using cached jsonpath_ng-1.7.0-py3-none-any.whl.metadata (18 kB)
Collecting makefun>=1.15.0 (from dlt[duckdb])
  Using cached makefun-1.15.6-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting orjson!=3.10.1,!=3.9.11,!=3.9.12,!=3.9.13,!=3.9.14,<4,>=3.6.7 (from dlt[duckdb])
  Using cached orjson-3.10.15-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Requirement already satisfied: packaging>=21.1 in /home/abrham/Desktop/Datatalks/DataTalks-Data-engineering-Training/week-one/.venv/lib/python3.12/site-packages (from dlt[duckdb]) (24.2)
Collecting pathvalidate>=2.5.2 (from dlt[duckdb])
  Using cached pathvalidate-3.2.3-py3-none-any.whl.metadata (12 kB)
Collecting pendulum>=2.1.2 (from dlt[duckdb])
  Using cached pendulum-3.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.9 kB)
Collecting pluggy>=1.3.0 (from dlt[duckdb])
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: pytz>=2022.6 in /home/abrham/Desktop/Datatalks/DataTalks-Data-engineering-Training/week-one/.venv/lib/python3.12/site-packages (from dlt[duckdb]) (2024.2)
Collecting requests>=2.26.0 (from dlt[duckdb])
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting requirements-parser>=0.5.0 (from dlt[duckdb])
  Using cached requirements_parser-0.11.0-py3-none-any.whl.metadata (4.7 kB)
Collecting rich-argparse<2.0.0,>=1.6.0 (from dlt[duckdb])
  Using cached rich_argparse-1.7.0-py3-none-any.whl.metadata (14 kB)
Collecting semver>=3.0.0 (from dlt[duckdb])
  Using cached semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting setuptools>=65.6.0 (from dlt[duckdb])
  Using cached setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
Collecting simplejson>=3.17.5 (from dlt[duckdb])
  Using cached simplejson-3.20.1-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting tenacity>=8.0.2 (from dlt[duckdb])
  Using cached tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)
Collecting tomlkit>=0.11.3 (from dlt[duckdb])
  Using cached tomlkit-0.13.2-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/abrham/Desktop/Datatalks/DataTalks-Data-engineering-Training/week-one/.venv/lib/python3.12/site-packages (from dlt[duckdb]) (4.12.2)
Requirement already satisfied: tzdata>=2022.1 in /home/abrham/Desktop/Datatalks/DataTalks-Data-engineering-Training/week-one/.venv/lib/python3.12/site-packages (from dlt[duckdb]) (2024.2)
Collecting gitdb<5,>=4.0.1 (from gitpython>=3.1.29->dlt[duckdb])
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting ply (from jsonpath-ng>=1.5.3->dlt[duckdb])
  Using cached ply-3.11-py2.py3-none-any.whl.metadata (844 bytes)
Requirement already satisfied: python-dateutil>=2.6 in /home/abrham/Desktop/Datatalks/DataTalks-Data-engineering-Training/week-one/.venv/lib/python3.12/site-packages (from pendulum>=2.1.2->dlt[duckdb]) (2.9.0.post0)
Collecting time-machine>=2.6.0 (from pendulum>=2.1.2->dlt[duckdb])
  Using cached time_machine-2.16.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.26.0->dlt[duckdb])
  Using cached charset_normalizer-3.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (35 kB)
Collecting idna<4,>=2.5 (from requests>=2.26.0->dlt[duckdb])
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.26.0->dlt[duckdb])
  Using cached urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests>=2.26.0->dlt[duckdb])
  Using cached certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Collecting types-setuptools>=69.1.0 (from requirements-parser>=0.5.0->dlt[duckdb])
  Using cached types_setuptools-75.8.0.20250210-py3-none-any.whl.metadata (2.2 kB)
Collecting rich>=11.0.0 (from rich-argparse<2.0.0,>=1.6.0->dlt[duckdb])
  Using cached rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython>=3.1.29->dlt[duckdb])
  Using cached smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: six>=1.5 in /home/abrham/Desktop/Datatalks/DataTalks-Data-engineering-Training/week-one/.venv/lib/python3.12/site-packages (from python-dateutil>=2.6->pendulum>=2.1.2->dlt[duckdb]) (1.17.0)
Collecting markdown-it-py>=2.2.0 (from rich>=11.0.0->rich-argparse<2.0.0,>=1.6.0->dlt[duckdb])
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/abrham/Desktop/Datatalks/DataTalks-Data-engineering-Training/week-one/.venv/lib/python3.12/site-packages (from rich>=11.0.0->rich-argparse<2.0.0,>=1.6.0->dlt[duckdb]) (2.19.1)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=11.0.0->rich-argparse<2.0.0,>=1.6.0->dlt[duckdb])
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached duckdb-1.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20.2 MB)
Using cached fsspec-2025.2.0-py3-none-any.whl (184 kB)
Using cached GitPython-3.1.44-py3-none-any.whl (207 kB)
Using cached giturlparse-0.12.0-py2.py3-none-any.whl (15 kB)
Using cached hexbytes-1.3.0-py3-none-any.whl (4.9 kB)
Using cached humanize-4.12.0-py3-none-any.whl (127 kB)
Using cached jsonpath_ng-1.7.0-py3-none-any.whl (30 kB)
Using cached makefun-1.15.6-py2.py3-none-any.whl (22 kB)
Using cached orjson-3.10.15-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (130 kB)
Using cached pathvalidate-3.2.3-py3-none-any.whl (24 kB)
Using cached pendulum-3.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (384 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (767 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached requirements_parser-0.11.0-py3-none-any.whl (14 kB)
Using cached rich_argparse-1.7.0-py3-none-any.whl (25 kB)
Using cached semver-3.0.4-py3-none-any.whl (17 kB)
Using cached setuptools-75.8.0-py3-none-any.whl (1.2 MB)
Using cached simplejson-3.20.1-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (152 kB)
Using cached tenacity-9.0.0-py3-none-any.whl (28 kB)
Using cached tomlkit-0.13.2-py3-none-any.whl (37 kB)
Using cached dlt-1.6.1-py3-none-any.whl (884 kB)
Using cached certifi-2025.1.31-py3-none-any.whl (166 kB)
Using cached charset_normalizer-3.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (145 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached rich-13.9.4-py3-none-any.whl (242 kB)
Using cached time_machine-2.16.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33 kB)
Using cached types_setuptools-75.8.0.20250210-py3-none-any.whl (71 kB)
Using cached urllib3-2.3.0-py3-none-any.whl (128 kB)
Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached smmap-5.0.2-py3-none-any.whl (24 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: ply, makefun, urllib3, types-setuptools, tomlkit, tenacity, smmap, simplejson, setuptools, semver, PyYAML, pluggy, pathvalidate, orjson, mdurl, jsonpath-ng, idna, humanize, hexbytes, giturlparse, fsspec, duckdb, charset-normalizer, certifi, time-machine, requirements-parser, requests, markdown-it-py, gitdb, rich, pendulum, gitpython, rich-argparse, dlt
Successfully installed PyYAML-6.0.2 certifi-2025.1.31 charset-normalizer-3.4.1 dlt-1.6.1 duckdb-1.2.0 fsspec-2025.2.0 gitdb-4.0.12 gitpython-3.1.44 giturlparse-0.12.0 hexbytes-1.3.0 humanize-4.12.0 idna-3.10 jsonpath-ng-1.7.0 makefun-1.15.6 markdown-it-py-3.0.0 mdurl-0.1.2 orjson-3.10.15 pathvalidate-3.2.3 pendulum-3.0.0 pluggy-1.5.0 ply-3.11 requests-2.32.3 requirements-parser-0.11.0 rich-13.9.4 rich-argparse-1.7.0 semver-3.0.4 setuptools-75.8.0 simplejson-3.20.1 smmap-5.0.2 tenacity-9.0.0 time-machine-2.16.0 tomlkit-0.13.2 types-setuptools-75.8.0.20250210 urllib3-2.3.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
import dlt
from dlt.sources.helpers.rest_client import RESTClient
from dlt.sources.helpers.rest_client.paginators import PageNumberPaginator



# Define the API resource for NYC taxi data
@dlt.resource(name="ny_taxi_trip")   # <--- The name of the resource (will be used as the table name)
def ny_taxi():
    client = RESTClient(
        base_url="https://us-central1-dlthub-analytics.cloudlt_dfunctions.net/data_engineering_zoomcamp_api",
        paginator=PageNumberPaginator(
            base_page=1,
            total_path=None
        )
    )

    for page in client.paginate("data_engineering_zoomcamp_api"):    # <--- API endpoint for retrieving taxi ride data
        yield page   # <--- yield data to manage memory


pipeline = dlt.pipeline(
    pipeline_name="ny_taxi_pipeline",
    destination="duckdb",
    dataset_name="ny_taxi_data"
)

In [9]:
load_info = pipeline.run(ny_taxi)
print(load_info)

Pipeline ny_taxi_pipeline load step completed in 2.20 seconds
1 load package(s) were loaded to destination duckdb and into dataset ny_taxi_data
The duckdb destination used duckdb:////home/abrham/Desktop/Datatalks/DataTalks-Data-engineering-Training/week-three/workshop/ny_taxi_pipeline.duckdb location to store data
Load package 1739787990.777739 is LOADED and contains no failed jobs

In [16]:
dlt_dlt_df = pipeline.dataset(dataset_type="default").ny_taxi_trip.dlt_df()

In [17]:
dlt_dlt_df

,end_lat,end_lon,fare_amt,passenger_count,payment_type,start_lat,start_lon,tip_amt,tolls_amt,total_amt,trip_distance,trip_dropoff_date_time,trip_pickup_date_time,surcharge,vendor_name,_dlt_load_id,_dlt_id,store_and_forward
0,40.742963,-73.980072,45.0,1,Credit,40.641525,-73.787442,9.0,4.15,58.15,17.52,2009-06-14 23:48:00+00:00,2009-06-14 23:23:00+00:00,0.0,VTS,1739787990.777739,229PIyXaSwJv/g,NaN
1,40.740187,-74.005698,6.5,1,Credit,40.722065,-74.009767,1.0,0.00,8.50,1.56,2009-06-18 17:43:00+00:00,2009-06-18 17:35:00+00:00,1.0,VTS,1739787990.777739,43JE+5/9VVuH2Q,NaN
2,40.718043,-74.004745,12.5,5,Credit,40.761945,-73.983038,2.0,0.00,15.50,3.37,2009-06-10 18:27:00+00:00,2009-06-10 18:08:00+00:00,1.0,VTS,1739787990.777739,bbtqGR3c9roMfg,NaN
3,40.739637,-73.985233,4.9,1,CASH,40.749802,-73.992247,0.0,0.00,5.40,1.11,2009-06-14 23:58:00+00:00,2009-06-14 23:54:00+00:00,0.5,VTS,1739787990.777739,tQa3LxKhQqSCRg,NaN
4,40.730032,-73.852693,25.7,1,CASH,40.776825,-73.949233,0.0,4.15,29.85,11.09,2009-06-13 13:23:00+00:00,2009-06-13 13:01:00+00:00,0.0,VTS,1739787990.777739,8LcxGUqf18f0Hg,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,40.783522,-73.970690,5.7,1,CASH,40.778560,-73.953660,0.0,0.00,5.70,1.16,2009-06-19 11:28:00+00:00,2009-06-19 11:22:00+00:00,0.0,VTS,1739787990.777739,wFFclTkItJ0Mew,NaN
9996,40.777200,-73.964197,4.1,1,CASH,40.779800,-73.974297,0.0,0.00,4.10,0.89,2009-06-17 07:43:00+00:00,2009-06-17 07:41:00+00:00,0.0,VTS,1739787990.777739,prVwGMujUWE0LA,NaN
9997,40.780172,-73.957617,6.1,1,CASH,40.788388,-73.976758,0.0,0.00,6.10,1.30,2009-06-19 11:46:00+00:00,2009-06-19 11:39:00+00:00,0.0,VTS,1739787990.777739,TCT2FwiKaUolkA,NaN
9998,40.777342,-73.957242,5.7,1,CASH,40.773828,-73.956690,0.0,0.00,6.20,0.97,2009-06-17 04:19:00+00:00,2009-06-17 04:13:00+00:00,0.5,VTS,1739787990.777739,t/PBj5Ze0yjo1w,NaN
9999,40.757122,-73.986293,6.5,1,Credit,40.756313,-73.972948,2.0,0.00,8.50,0.92,2009-06-17 08:34:00+00:00,2009-06-17 08:24:00+00:00,0.0,VTS,1739787990.777739,+/r119rNiAm9og,NaN

In [ ]:
average_value = dlt_dlt_df['Value'].mean()
print("Average Value:", average_value)

In [ ]:
import duckdb


# A database '<pipeline_name>.duckdb' was created in working directory so just connect to it

# Connect to the DuckDB database
conn = duckdb.connect(f"{pipeline.pipeline_name}.duckdb")

# Set search path to the dataset
conn.sql(f"SET search_path = '{pipeline.dataset_name}'")

# Describe the dataset
conn.sql("DESCRIBE").dlt_df()

,database,schema,name,column_names,column_types,temporary
0,ny_taxi_pipeline,ny_taxi_data,_dlt_loads,"[load_id, schema_name, status, inserted_at, sc...","[VARCHAR, VARCHAR, BIGINT, TIMESTAMP WITH TIME...",False
1,ny_taxi_pipeline,ny_taxi_data,_dlt_pipeline_state,"[version, engine_version, pipeline_name, state...","[BIGINT, BIGINT, VARCHAR, VARCHAR, TIMESTAMP W...",False
2,ny_taxi_pipeline,ny_taxi_data,_dlt_version,"[version, engine_version, inserted_at, schema_...","[BIGINT, BIGINT, TIMESTAMP WITH TIME ZONE, VAR...",False
3,ny_taxi_pipeline,ny_taxi_data,ny_taxi_trip,"[end_lat, end_lon, fare_amt, passenger_count, ...","[DOUBLE, DOUBLE, DOUBLE, BIGINT, VARCHAR, DOUB...",False

In [19]:
import pandas as pd

# Convert columns to datetime
dlt_df['trip_pickup_date_time'] = pd.to_datetime(dlt_df['trip_pickup_date_time'])
dlt_df['trip_dropoff_date_time'] = pd.to_datetime(dlt_df['trip_dropoff_date_time'])

# Calculate trip duration in minutes
dlt_df['trip_duration'] = (dlt_df['trip_dropoff_date_time'] - dlt_df['trip_pickup_date_time']).dt.total_seconds() / 60

# Calculate the average trip duration
average_trip_duration = dlt_df['trip_duration'].mean()
print("Average Trip Duration (minutes):", average_trip_duration)

Average Trip Duration (minutes): 12.304918333333335